name: anime_dbt
version: "1.0.0"
config-version: 2

profile: anime_dbt

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  anime_dbt:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
